-- Role: "PS2JaegerAccountbot"
-- DROP ROLE IF EXISTS "PS2JaegerAccountbot";

CREATE ROLE "PS2JaegerAccountbot" WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  PASSWORD 'PG_PASS';